/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { SensorDataRegistry } from "./SensorDataRegistry";
export * as factories from "./factories";
export { SensorDataRegistry__factory } from "./factories/SensorDataRegistry__factory";
