/*
  Blockchain-Enabled Secure IoT Monitoring System
  RECEIVER ESP32

  Hardware:
  - ESP32 NodeMCU ESP-32S 30-pin
  - NRF24L01
  - RGB LED
  - Push Button
  - Buzzer

  Data flow:

  NRF24L01
       ↓
  ESP32 Receiver
       ↓
  Wi-Fi
       ↓
  HTTPS API
       ↓
  Website Backend
       ↓
  Database / Blockchain
       ↓
  Website Dashboard
*/

#include <WiFi.h>
#include <WiFiClientSecure.h>
#include <HTTPClient.h>
#include <SPI.h>
#include <RF24.h>

// =====================================================
// USER CONFIGURATION
// =====================================================

// Put your Wi-Fi name here
const char* WIFI_SSID = "sundar (iQOO Z10 5G)";

// Put your Wi-Fi password here
const char* WIFI_PASSWORD = "0987654321123";

// IMPORTANT:
// Put your PUBLIC backend API endpoint here.
//
// Example:
// https://your-domain.com/api/v1/sensor-data
//
// DO NOT use:
// localhost
// 127.0.0.1
// 192.168.x.x

const char* API_URL =
  "https://nrf24l01-monitoring.vercel.app/api/v1/sensor-data";

// Device identifier used by your website/backend
const char* DEVICE_ID = "receiver-01";

// Device API key generated by your backend
const char* DEVICE_API_KEY = "rcvr_TPWYBsqHVYd7jG0qHsbIrAdyKMl";

// =====================================================
// NRF24 PINS
// =====================================================

#define NRF_CE 4
#define NRF_CSN 5

// =====================================================
// RECEIVER OUTPUT PINS
// =====================================================

#define RGB_RED 25
#define RGB_GREEN 26
#define RGB_BLUE 33

#define BUTTON_PIN 32

#define BUZZER_PIN 13

// =====================================================
// NRF24 CONFIGURATION
// MUST MATCH TRANSMITTER
// =====================================================

const uint64_t RADIO_ADDRESS = 0x4E4F444531LL;

const uint8_t RADIO_CHANNEL = 108;

const rf24_datarate_e RADIO_DATA_RATE = RF24_250KBPS;

const rf24_pa_dbm_e RADIO_PA_LEVEL = RF24_PA_LOW;

// =====================================================
// SENSOR PACKET
// MUST EXACTLY MATCH TRANSMITTER
// =====================================================

struct SensorPacket {

  float temperature;

  float humidity;

  bool motion;

  uint32_t packet_number;
};

// =====================================================
// OBJECTS
// =====================================================

RF24 radio(NRF_CE, NRF_CSN);

SensorPacket packet;

// =====================================================
// VARIABLES
// =====================================================

unsigned long lastPacketReceived = 0;

unsigned long lastWiFiCheck = 0;

unsigned long lastHeartbeat = 0;

bool buzzerAcknowledged = false;

bool lastMotionState = false;

uint32_t lastPacketNumber = 0;

// Device considered offline after this period
const unsigned long DEVICE_TIMEOUT = 10000;

// Wi-Fi reconnect interval
const unsigned long WIFI_RECONNECT_INTERVAL = 10000;

// Heartbeat interval
const unsigned long HEARTBEAT_INTERVAL = 30000;

// =====================================================
// RGB LED FUNCTIONS
// =====================================================

void rgbOff() {

  digitalWrite(RGB_RED, LOW);
  digitalWrite(RGB_GREEN, LOW);
  digitalWrite(RGB_BLUE, LOW);
}

void rgbGreen() {

  digitalWrite(RGB_RED, LOW);
  digitalWrite(RGB_GREEN, HIGH);
  digitalWrite(RGB_BLUE, LOW);
}

void rgbRed() {

  digitalWrite(RGB_RED, HIGH);
  digitalWrite(RGB_GREEN, LOW);
  digitalWrite(RGB_BLUE, LOW);
}

void rgbBlue() {

  digitalWrite(RGB_RED, LOW);
  digitalWrite(RGB_GREEN, LOW);
  digitalWrite(RGB_BLUE, HIGH);
}

// =====================================================
// WIFI
// =====================================================

void connectWiFi() {

  if (WiFi.status() == WL_CONNECTED) {
    return;
  }

  Serial.println();
  Serial.println("Connecting to Wi-Fi...");

  WiFi.mode(WIFI_STA);

  WiFi.begin(WIFI_SSID, WIFI_PASSWORD);

  unsigned long start = millis();

  while (
    WiFi.status() != WL_CONNECTED &&
    millis() - start < 15000
  ) {

    delay(500);

    Serial.print(".");
  }

  Serial.println();

  if (WiFi.status() == WL_CONNECTED) {

    Serial.println("Wi-Fi CONNECTED");

    Serial.print("IP Address: ");
    Serial.println(WiFi.localIP());

  } else {

    Serial.println("Wi-Fi connection FAILED");

  }
}

// =====================================================
// SEND SENSOR DATA TO WEBSITE BACKEND
// =====================================================

bool sendSensorData() {

  if (WiFi.status() != WL_CONNECTED) {

    Serial.println("Cannot send data: Wi-Fi offline");

    return false;
  }

  WiFiClientSecure client;

  // HTTPS certificate verification is disabled here
  // for easier ESP32 deployment.
  //
  // For production, replace with proper CA certificate
  // verification.

  client.setInsecure();

  HTTPClient https;

  Serial.println();
  Serial.println("Sending sensor data to backend...");

  if (!https.begin(client, API_URL)) {

    Serial.println("HTTPS connection initialization failed");

    return false;
  }

  https.setTimeout(8000);

  // Authentication - updated to expect "X-Device-API-Key"
  https.addHeader(
    "X-Device-API-Key",
    DEVICE_API_KEY
  );

  https.addHeader(
    "Content-Type",
    "application/json"
  );

  // ---------------------------------------------------
  // JSON DATA
  // ---------------------------------------------------

  String json = "{";

  json += "\"device_id\":\"";
  json += DEVICE_ID;
  json += "\",";

  json += "\"temperature\":";
  json += String(packet.temperature, 2);
  json += ",";

  json += "\"humidity\":";
  json += String(packet.humidity, 2);
  json += ",";

  json += "\"motion\":";
  json += packet.motion ? "true" : "false";
  json += ",";

  json += "\"packet_number\":";
  json += String(packet.packet_number);

  json += "}";

  Serial.println("JSON:");
  Serial.println(json);

  // ---------------------------------------------------
  // POST
  // ---------------------------------------------------

  int httpCode = https.POST(json);

  Serial.print("HTTP Status: ");
  Serial.println(httpCode);

  if (httpCode > 0) {

    String response = https.getString();

    Serial.println("Server Response:");
    Serial.println(response);

    https.end();

    if (httpCode >= 200 && httpCode < 300) {

      Serial.println("DATA UPLOAD SUCCESS");

      return true;
    }

  } else {

    Serial.print("HTTP Error: ");
    Serial.println(https.errorToString(httpCode));
  }

  https.end();

  return false;
}

// =====================================================
// LOCAL DEVICE STATUS
// =====================================================

void updateLocalOutputs() {

  if (millis() - lastPacketReceived > DEVICE_TIMEOUT) {

    // NRF24 communication timeout
    rgbBlue();

    digitalWrite(BUZZER_PIN, LOW);

    return;
  }

  // Motion detected
  if (packet.motion) {

    rgbRed();

    if (!buzzerAcknowledged) {
      digitalWrite(BUZZER_PIN, HIGH);
    }

  } else {

    rgbGreen();

    digitalWrite(BUZZER_PIN, LOW);

    buzzerAcknowledged = false;
  }
}

// =====================================================
// BUTTON
// =====================================================

void checkButton() {

  static bool previousButtonState = HIGH;

  bool currentButtonState = digitalRead(BUTTON_PIN);

  if (
    previousButtonState == HIGH &&
    currentButtonState == LOW
  ) {

    Serial.println("BUTTON PRESSED");

    buzzerAcknowledged = true;

    digitalWrite(BUZZER_PIN, LOW);

    delay(50);
  }

  previousButtonState = currentButtonState;
}

// =====================================================
// RECEIVE NRF24 DATA
// =====================================================

void receiveNRF24Data() {

  if (!radio.available()) {
    return;
  }

  while (radio.available()) {

    radio.read(
      &packet,
      sizeof(packet)
    );
  }

  // ---------------------------------------------------
  // VALIDATE DATA
  // ---------------------------------------------------

  if (isnan(packet.temperature) ||
      isnan(packet.humidity)) {

    Serial.println(
      "WARNING: Invalid sensor packet"
    );

    return;
  }

  if (packet.humidity < 0 ||
      packet.humidity > 100) {

    Serial.println(
      "WARNING: Invalid humidity"
    );

    return;
  }

  if (packet.temperature < -50 ||
      packet.temperature > 100) {

    Serial.println(
      "WARNING: Invalid temperature"
    );

    return;
  }

  // ---------------------------------------------------
  // PACKET RECEIVED
  // ---------------------------------------------------

  lastPacketReceived = millis();

  lastPacketNumber = packet.packet_number;

  Serial.println();
  Serial.println("================================");

  Serial.println("NRF24 DATA RECEIVED");

  Serial.print("Packet: ");
  Serial.println(packet.packet_number);

  Serial.print("Temperature: ");
  Serial.print(packet.temperature, 2);
  Serial.println(" °C");

  Serial.print("Humidity: ");
  Serial.print(packet.humidity, 2);
  Serial.println(" %");

  Serial.print("Motion: ");

  if (packet.motion) {
    Serial.println("DETECTED");
  } else {
    Serial.println("NO MOTION");
  }

  Serial.println("================================");

  // ---------------------------------------------------
  // MOTION STATE CHANGE
  // ---------------------------------------------------

  if (
    packet.motion &&
    !lastMotionState
  ) {

    Serial.println(">>> MOTION EVENT STARTED <<<");

    buzzerAcknowledged = false;
  }

  if (
    !packet.motion &&
    lastMotionState
  ) {

    Serial.println(">>> MOTION EVENT CLEARED <<<");
  }

  lastMotionState = packet.motion;

  // ---------------------------------------------------
  // SEND TO WEBSITE
  // ---------------------------------------------------

  sendSensorData();
}

// =====================================================
// SETUP
// =====================================================

void setup() {

  Serial.begin(115200);

  delay(1000);

  Serial.println();
  Serial.println("====================================");
  Serial.println("      IoT RECEIVER ESP32");
  Serial.println("====================================");

  // ---------------------------------------------------
  // GPIO
  // ---------------------------------------------------

  pinMode(RGB_RED, OUTPUT);

  pinMode(RGB_GREEN, OUTPUT);

  pinMode(RGB_BLUE, OUTPUT);

  pinMode(BUZZER_PIN, OUTPUT);

  pinMode(BUTTON_PIN, INPUT_PULLUP);

  rgbOff();

  digitalWrite(BUZZER_PIN, LOW);

  // ---------------------------------------------------
  // NRF24
  // ---------------------------------------------------

  if (!radio.begin()) {

    Serial.println(
      "CRITICAL ERROR: NRF24 NOT DETECTED"
    );

    rgbRed();

    while (true) {

      digitalWrite(BUZZER_PIN, HIGH);

      delay(200);

      digitalWrite(BUZZER_PIN, LOW);

      delay(200);
    }
  }

  radio.setChannel(RADIO_CHANNEL);

  radio.setDataRate(RADIO_DATA_RATE);

  radio.setPALevel(RADIO_PA_LEVEL);

  radio.setRetries(5, 15);

  radio.openReadingPipe(
    1,
    RADIO_ADDRESS
  );

  radio.startListening();

  Serial.println(
    "[OK] NRF24L01 initialized"
  );

  // ---------------------------------------------------
  // WIFI
  // ---------------------------------------------------

  connectWiFi();

  // ---------------------------------------------------
  // INITIAL STATUS
  // ---------------------------------------------------

  rgbBlue();

  Serial.println();
  Serial.println("RECEIVER READY");
  Serial.println("------------------------------------");

  Serial.print("Device ID: ");
  Serial.println(DEVICE_ID);

  Serial.println("Waiting for NRF24 data...");
}

// =====================================================
// LOOP
// =====================================================

void loop() {

  // ---------------------------------------------------
  // NRF24
  // ---------------------------------------------------

  receiveNRF24Data();

  // ---------------------------------------------------
  // BUTTON
  // ---------------------------------------------------

  checkButton();

  // ---------------------------------------------------
  // LOCAL STATUS
  // ---------------------------------------------------

  updateLocalOutputs();

  // ---------------------------------------------------
  // WIFI RECONNECT
  // ---------------------------------------------------

  if (
    millis() - lastWiFiCheck >
    WIFI_RECONNECT_INTERVAL
  ) {

    lastWiFiCheck = millis();

    if (WiFi.status() != WL_CONNECTED) {

      Serial.println(
        "Wi-Fi disconnected. Reconnecting..."
      );

      connectWiFi();
    }
  }

  // ---------------------------------------------------
  // HEARTBEAT
  // ---------------------------------------------------

  if (
    millis() - lastHeartbeat >
    HEARTBEAT_INTERVAL
  ) {

    lastHeartbeat = millis();

    Serial.println();
    Serial.println("========== RECEIVER STATUS ==========");

    Serial.print("Wi-Fi: ");

    if (WiFi.status() == WL_CONNECTED) {
      Serial.println("ONLINE");
    } else {
      Serial.println("OFFLINE");
    }

    Serial.print("Last NRF Packet: ");
    Serial.println(lastPacketNumber);

    Serial.print("Last Data Age: ");
    Serial.print(
      (millis() - lastPacketReceived) / 1000
    );
    Serial.println(" seconds");

    Serial.println("=====================================");
  }

  delay(5);
}
